---
# RetroPie configuration

- name: RetroPie!
  gather_facts: no
  hosts: all
  remote_user: pi

  tasks:
    - include: tasks/update.yml
      tags: update

    - include: tasks/controllers.yml
      tags: controllers

    - include: tasks/retroarch.yml
      tags: retroarch

    - include: tasks/theme.yml
      tags: theme

    - include: tasks/disable.yml
      tags: disable
    - include: tasks/enable.yml
      tags: enable

    - include: tasks/reboot.yml
      tags: restart

    - include: tasks/bios.yml
      tags: bios

    - include: tasks/roms.yml
      tags: roms

    - include: tasks/scraped.yml
      tags: scraped
